#!/usr/bin/env bash
DKR_IMAGE=postgres:latest
DKR_HOST_PORT=$1
DKR_CNT_NAME=$2
DKR_CNT_PATH=volpg-$DKR_CNT_NAME
GENPWD=`pwgen -1 15`
if [ -z "$DKR_HOST_PORT" ]; then
  echo "You must provide docker host port"
  exit 1
fi


if [ -z "$DKR_CNT_NAME" ]; then
  echo "You must provide container name"
  exit 1
fi
echo "PGSQL: Generated root password is '$GENPWD'"

docker run --name $DKR_CNT_NAME \
  -p $DKR_HOST_PORT:5432 \
  -e "POSTGRES_PASSWORD=$GENPWD" \
  -v $DKR_CNT_PATH:/var/lib/postgresql/data \
  -d $DKR_IMAGE
echo "Waiting for container '$DKR_CNT_NAME' to start ... " 


